"""Operational knowledge graph: ontology, ingestion, traversal and GraphRAG.

Neo4j is a soft dependency throughout. Every entry point either returns a typed
result or raises ``SourceUnavailable``; nothing in this package can halt an
investigation, and nothing collapses "found nothing" into "could not look".
"""

from __future__ import annotations

from aegis.graph.client import Neo4jClient
from aegis.graph.graphrag import (
    CommitSummary,
    GraphContext,
    GraphRAG,
    ScoredNode,
    apply_budget,
    score_nodes,
    temporal_boost,
)
from aegis.graph.ingest import (
    CallEdge,
    CommitRecord,
    DependencyEdge,
    DeploymentRecord,
    EndpointRecord,
    FileChange,
    IngestStats,
    InstanceRecord,
    ObservedCall,
    ServiceDiscoverySource,
    TopologyIngestor,
    TraceCallEdge,
    TraceTopologySource,
)
from aegis.graph.ontology import (
    NODES,
    RELATIONSHIPS,
    NodeLabel,
    NodeSpec,
    RelSpec,
    RelType,
    constraints_cypher,
    natural_key,
    node_spec,
    rel_spec,
    validate_edge,
    validate_label,
    validate_node_properties,
    validate_rel_type,
)
from aegis.graph.traversal import (
    MAX_DEPTH,
    CausalPath,
    DeploymentSummary,
    GraphEdge,
    GraphNode,
    GraphTraversal,
    QueryRecord,
    QueryRecorder,
    SharedDependency,
    SimilarIncident,
    TeamRef,
    provenance_uri,
    query_hash,
    rendered_cypher,
)

__all__ = [
    "MAX_DEPTH",
    "NODES",
    "RELATIONSHIPS",
    "CallEdge",
    "CausalPath",
    "CommitRecord",
    "CommitSummary",
    "DependencyEdge",
    "DeploymentRecord",
    "DeploymentSummary",
    "EndpointRecord",
    "FileChange",
    "GraphContext",
    "GraphEdge",
    "GraphNode",
    "GraphRAG",
    "GraphTraversal",
    "IngestStats",
    "InstanceRecord",
    "Neo4jClient",
    "NodeLabel",
    "NodeSpec",
    "ObservedCall",
    "QueryRecord",
    "QueryRecorder",
    "RelSpec",
    "RelType",
    "ScoredNode",
    "ServiceDiscoverySource",
    "SharedDependency",
    "SimilarIncident",
    "TeamRef",
    "TopologyIngestor",
    "TraceCallEdge",
    "TraceTopologySource",
    "apply_budget",
    "constraints_cypher",
    "natural_key",
    "node_spec",
    "provenance_uri",
    "query_hash",
    "rel_spec",
    "rendered_cypher",
    "score_nodes",
    "temporal_boost",
    "validate_edge",
    "validate_label",
    "validate_node_properties",
    "validate_rel_type",
]
